<?php

/**
 * @file
 * Primary module hooks for Helsinki-profiili module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\helfi_helsinki_profiili\HelsinkiProfiiliUserData;
use Drupal\helfi_helsinki_profiili\ProfileDataException;
use Drupal\user\UserInterface;

/**
 * OpenID Connect post authorize hook.
 *
 * This hook runs after a user has been authorized and claims have been mapped
 * to the user's account.
 *
 * A popular use case for this hook is to saving token and additional identity
 * provider related information to the user's Drupal session (private temp
 * store).
 *
 * @param \Drupal\user\UserInterface $account
 *   User account object of the authorized user.
 * @param array $context
 *   An associative array with context information:
 *   - tokens:         An array of tokens.
 *   - user_data:      An array of user and session data.*
 *   - plugin_id:      The plugin identifier.
 *   - sub:            The remote user identifier.
 *
 * @ingroup openid_connect_api
 */
function helfi_helsinki_profiili_openid_connect_post_authorize(UserInterface $account, array $context) {


  // Remove all existing roles.
  array_map(
    fn (string $rid) => $account->removeRole($rid),
    $account->getRoles(FALSE)
  );

  try {
    // add strong auth for strong auth and weak for other.
    // @todo: this will need to change when we actually see what the difference here is.
    if ($context["user_data"]["loa"] == 'substantial') {
      $account->addRole(getenv('HP_USER_ROLE_STRONG'));
    } else {
      $account->addRole(getenv('HP_USER_ROLE_WEAK'));
    }
    $account->save();
  } catch (\Drupal\Core\Entity\EntityStorageException $e) {
    $d = 'adsf';
  }

  /** @var Drupal\helfi_helsinki_profiili\HelsinkiProfiiliUserData */
  $profileDAO = \Drupal::service('helfi_helsinki_profiili.userdata');
  try {
    // set user data from openid
    $profileDAO->setUserData($context['user_data']);
    // fetch HelsinkiProfile data
    try {
      $data = $profileDAO->getUserProfileData();

      if ($data == NULL) {
        \Drupal::messenger()
          ->addWarning('User logged in, no profiledata found.');
      }
      else {
        \Drupal::messenger()->addStatus('User logged in and data fetched');
      }


    } catch (ProfileDataException $e) {
      \Drupal::messenger()->addStatus($e->getMessage());
    }
  } catch (\GuzzleHttp\Exception\GuzzleException $e) {
    \Drupal::messenger()->addError('User profile data fetch failed');
  }

}

/**
 * Implements hook_user_logout().
 */
function helfi_helsinki_profiili_user_logout(\Drupal\Core\Session\AccountProxyInterface $account) {
  /** @var Drupal\helfi_helsinki_profiili\HelsinkiProfiiliUserData */
  $helsinkiProfiili = \Drupal::service('helfi_helsinki_profiili.userdata');
  $helsinkiProfiili->clearCache();
}
